### ISSUE TITLE
mariadb-galera-server package has different name on CentOS 7

### ISSUE THREAD

**Issue by bbgrk** [devops/ansible-role-mariadb-galera#1]
``` bash
TASK [ansible-role-mariadb-galera : [CentOS] Ensure MariaDB packages are installed.] ***
task path: /etc/ansible/nextcloud/roles/external/ansible-role-mariadb-galera/tasks/setup-RedHat.yml:13
ok: [db2] => (item=[u'mariadb-galera-server', u'MySQL-python', u'rsync', u'xinetd']) => {"changed": false, "failed": true, "item": ["mariadb-galera-server", "MySQL-python", "rsync", "xinetd"], "msg": "No Package matching 'mariadb-galera-server' found available, installed or updated", "rc": 0, "results": []}
```

Fix:

``` yaml
# vars file RedHat.yml

mariadb_daemon: mariadb
__mariadb_packages:
  - MariaDB-Galera-server
  - MySQL-python
  - rsync
  - xinetd
```
