### ISSUE TITLE
monitoring user doesn't need all privivileges on all databases

### ISSUE THREAD

**Issue by c4m4** [devops/ansible-role-mariadb-galera#3]
the monitoring user has privileges to do everything:

```
- name: Ensure clustercheck users are present.
  mysql_user:
    name: "{{ galera_clustercheck_username }}"
    host: "localhost"
    password: "{{ galera_clustercheck_password }}"
    priv: "*.*:ALL"
    state: present
run_once: True
```
